services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "8929:80"  
      - "2222:22" 
      - "443:443"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
     

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"  
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    
volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:



